### ISSUE TITLE
[P3B-3] Shopping list information #1 

### ISSUE THREAD

**Issue by s1155030186** [s1155002037/shop03#1]
localStorage is filled with following data style:
{bookid,quantity, bookname, bookprice}

By requirement, it should
store {pid, number}
request {prod_name, price} from AJAX
![11212402_10205665650294492_1515446157_n](https://cloud.githubusercontent.com/assets/10598196/7539916/f8919fe0-f5dc-11e4-9da6-31a66a2311e3.jpg)
![1472287_10205665680335243_1907871988_n](https://cloud.githubusercontent.com/assets/10598196/7539925/05581506-f5dd-11e4-9b88-08ec8a950c59.jpg)
![11225770_10205665680575249_1052283173_n](https://cloud.githubusercontent.com/assets/10598196/7539933/10d3f698-f5dd-11e4-8687-520b58352887.jpg)
![11245229_10205665680815255_1715792386_n](https://cloud.githubusercontent.com/assets/10598196/7539941/1d51ad98-f5dd-11e4-9a54-293de31c4282.jpg)

Users may change the localStorage so that users can buy products to be cheapest

It expected to change back to a normal product information by sending request to server

From the photo, we can see that when product is updated, the shopping list would not updated. The wrong decision may be made due to wrong. Or you send the whole things to server and server does not check the relation of the product, it will receive an unexpected total from the client.
Moreover, it may cause worse user experience on using this website as the user may mislead by the wrong amount on the shopping list. 

prossible fix: Request the price and name by ajax request by using (pid,quantity) and not trust the client local storage directly

**Comment by s1155002037** [comment]
The price and name of products are got at server side by ajax, you can check the source code for sure. The localStorage stored the price information but only pid and quantity are sent as parameters.

**Comment by s1155030186** [comment]
i know what u mean, but after the ajax pull down the price, the price can be change on the client side by using javascript. After refresh the page, the shopping cart is restored by using localStorage only.

here is the function u use for the shopping list restoration which didn't call any server side to check the amount again.

var shoppingCartItems = JSON.parse(localStorage.shoppingCart);
        $.each(shoppingCartItems, function(id, bookItem){
            total += bookItem.quantity*bookItem.bookPrice;
        });

**Comment by s1155002037** [comment]
The server will recalculate the price again and will not receive any information about the price at the client side. The following codes can prove this. Following codes are from routes/checkout which handles the shopping cart. The code you paste is only for client side shopping cart display.

router.get('/',isLoggedIn, function(req, res){
    var fullUrl = req.protocol + '://' + req.get('host') + req.baseUrl;
    console.log('req.fullUrl', fullUrl);
    var booksToBuy = [];
    var booksToBuy2 = [];
    models.Product.findAll().then(function(products){
      var total = 0;
      products.forEach(function(product){
        var quantity = 0;
        var price = 0;
        //console.log('pid = '+product.id);
        //console.log('query id = '+typeof(req.query.id[1]));
        //console.log('== '+req.query.id.indexOf('1'));
        if(req.query.id.indexOf(product.id.toString()) != -1){
          console.log(product.productName);
          quantity = req.query.quantity[req.query.id.indexOf(product.id.toString())];
          price = parseFloat(Math.round(product.productPrice_100)/100).toFixed(2);
          subtotal = parseFloat(product.productPrice)_parseFloat(quantity);
          total = total + subtotal;
          var bookToBuy = {'sku':req.query.id[req.query.id.indexOf(product.id.toString())], 'name':product.productName, 'price':price,'currency':'USD','quantity':quantity};
          booksToBuy.push(bookToBuy);
        }
      });
      total = parseFloat(Math.round(total*100)/100).toFixed(2);

**Comment by hkop2002** [comment]
[TA comment] Non-security issue. Not fixed.
The price should also be correct on client side
